sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - scripts/install-apache-mod-wsgi
install:
  - pip install coveralls
  - python setup.py install
script:
  - scripts/collect-full-coverage
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
