sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - pip install coveralls
  - python setup.py install
script:
  coverage run setup.py test
after_success:
  coveralls
